


clean: 
	rm -rf quartus.*
	rm -rf *.log
	rm -rf *.rec

# running source may not work from the makefile, in that case just run source from the command line to use aliases
setup_server:
	cp utils/.aliases ../../
	cp utils/.bashrc ../../
	source ~/.bashrc 



